version: '2'
services:
  socialmediaintegration:
    build:
      context: ./
    image: socialmediaintegration
    depends_on: 
      - mongo
    ports:
      - 3000:3000
    networks:
      - nodeapp-network
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /data/db
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge